apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: renewed-dragonfly-python 
  janus-idp.io/tekton: renewed-dragonfly-python
  backstage.io/kubernetes-id: renewed-dragonfly-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: renewed-dragonfly-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  