apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: renewed-dragonfly-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: renewed-dragonfly-python 
  name: renewed-dragonfly-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: renewed-dragonfly-python 
